hot fix

diff --git a/.github/workflows/FrontCi.yml b/.github/workflows/FrontCi.yml
--- a/.github/workflows/FrontCi.yml
+++ b/.github/workflows/FrontCi.yml
@@ -60,17 +60,41 @@ jobs:
           git push
 
   start_deploy_render:
-    name: Iniciar el despliegue en Render
+    name: Iniciar el despligue en Render
     runs-on: ubuntu-latest
-
     steps:
       - name: Desplegar en Render
         run: |
-          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST "https://api.render.com/v1/services/srv-cqr6m5l6l47c739pbda0/deploys" -H "Authorization: Bearer $RENDER_API_KEY")
+          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST "https://api.render.com/deploy/srv-cqr6m5l6l47c739pbda0" -H "key: $RENDER_API_KEY")
           if [ $response -eq 200 ]; then
             echo "Deployment successful"
           else
             echo "Deployment failed with HTTP status code $response"
+            exit 1
           fi
+
+        env:
+          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
+
+  deploy_in_process:
+    name: Despliegue en proceso
+    runs-on: ubuntu-latest
+    needs: start_deploy_render
+    if: success()
+    steps:
+      - name: Despliegue en proceso
+        run:  |
+          deploy_status="pending"
+          while [ "$deploy_status" != "live" ]; do
+            response=$(curl -s -H "Authorization: Bearer $RENDER_API_KEY" "https://api.render.com/v1/services/srv-cqr6m5l6l47c739pbda0/deploys")
+            echo "Render API response: $response"
+            deploy_status=$(echo $response | jq -r '.[0].deploy.status') 
+            echo "Current deploy status: $deploy_status"
+            if [ "$deploy_status" == "failed" ]; then
+              echo "Deployment failed."
+            fi
+            sleep 5
+          done
+          echo "Deployment completed successfully."
         env:
           RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
